# Generated by Django 6.0.3 on 2026-03-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(default=42, upload_to='pets/'),
            preserve_default=False,
        ),
    ]
